EXTRA_ALL := 
EXTRA_CFLAGS := -Wdeclaration-after-statement -fstack-protector --param=ssp-buffer-size=4 -Os -pipe -fomit-frame-pointer
EXTRA_INSTALL := 
EXTRA_LDFLAGS := -fstack-protector
EXTRA_SRCS := 
EXTRA_UNINSTALL := 
PTHREAD := 
XMMS_INPUT_PLUGIN_DIR := 
VERSION := 0.0.91+git20110109
prefix := /usr/local
exec_prefix := /usr/local
bindir := /usr/local/bin
libdir := /usr/local/lib
mandir := /usr/local/man
docdir := /usr/local/share/doc/gbsplay
localedir := /usr/local/share/locale
sysconfdir := /etc
CC := gcc
BUILDCC := gcc
HOSTCC := gcc
build_contrib := yes
build_test := yes
build_xmmsplugin := no
have_xgettext := yes
use_i18n := yes
use_sharedlibgbs := no
cygwin_build := no
libaudio_flags := 
plugout_devdsp := yes
plugout_alsa := yes
plugout_midi := yes
plugout_nas :=
plugout_stdout := yes
