.\" This manpage 2003 (C) by Christian Garbs <mitch@cgarbs.de>
.\" Licensed under GNU GPL.
.TH "gbsinfo" "1" "0.0.2" "Tobias Diedrich" "Gameboy sound player"
.SH "NAME"
.LP
\fBgbsinfo\fR \- display Gameboy sound file information
.SH "SYNOPSIS"
\&\fBgbsinfo\fR \fIgbs\-file\fR
.SH "DESCRIPTION"
gbsinfo displays information about a Gameboy module dump (.GBS format).
.SH "PARAMETERS"
.TP
\fIgbs\-file\fR
The sound file to read.  Must be in uncompressed .GBS format.
.SH "SEE ALSO"
\fIgbsplay\fR(1)
.SH "BUG REPORTS"
If you encounter bugs, please report them to <\fIranma@gmx.at\fR>.
.SH "AUTHOR"
gbsinfo was written by Tobias Diedrich <\fIranma@gmx.at\fR> (with contributions from others, see README).
.SH "COPYRIGHT"
gbsinfo is licensed under GNU GPL.
