.\" $Id: gbsinfo.in.1,v 1.4 2004/04/02 09:23:11 mitch Exp $
.\" This manpage 2003-2004 (C) by Christian Garbs <mitch@cgarbs.de>
.\" Licensed under GNU GPL.
.TH "gbsinfo" "1" "%%%VERSION%%%" "Tobias Diedrich" "Gameboy sound player"
.SH "NAME"
.LP
\fBgbsinfo\fR \- display Gameboy sound file information
.SH "SYNOPSIS"
\fBgbsinfo\fR [\fI-h\fR|\fI-V\fR] \fIgbs\-file\fR
.SH "DESCRIPTION"
gbsinfo displays information about a Gameboy module dump (.GBS format).
.SH "OPTIONS"
.TP
\fI\-h\fR
Display short help and exit.
.TP
\fI\-V\fR
Display version number and exit.
.SH "PARAMETERS"
.TP
\fIgbs\-file\fR
The sound file to read.  Must be in uncompressed .GBS format.
.SH "SEE ALSO"
\fIgbsplay\fR(1)
.SH "BUG REPORTS"
If you encounter bugs, please report them via \fIhttp://gbsplay.berlios.de/\fR or write to <\fIgbsplay-dev@lists.berlios.de\fR>.
.SH "AUTHOR"
gbsinfo was written by Tobias Diedrich <\fIranma@gmx.at\fR> (with contributions from others, see README).
.SH "COPYRIGHT"
gbsinfo is licensed under GNU GPL.
