.\" $Id: gbsplay.in.1,v 1.13 2004/04/05 12:08:36 mitch Exp $
.\" This manpage 2003-2004 (C) by Christian Garbs <mitch@cgarbs.de>
.\" Licensed under GNU GPL.
.TH "gbsplay" "1" "%%%VERSION%%%" "Tobias Diedrich" "Gameboy sound player"
.SH "NAME"
.LP
\fBgbsplay\fR \- Gameboy sound player
.SH "SYNOPSIS"
\fBgbsplay\fR [\fIoptions\fR] \fIgbs\-file\fR [\fIstart\-subsong\fR [\fIstop\-subsong\fR] ]
.SH "DESCRIPTION"
gbsplay emulates the sound hardware of the Nintendo Gameboy.  It
is able to play the sounds from a Gameboy module dump (.GBS format)
over /dev/dsp.
.SH "OPTIONS"
.TP
\fI\-E endian\fR
Set endian to \fIendian\fR.  Valid values are \fIb\fR, \fIl\fR and \fIn\fR for big, little and native endian respectively.
.TP
\fI\-f fadeout\-time\fR
Set fadeout time to \fIsubsong\-gap\fR seconds.  Instead of cutting of the subsong hard, do a soft fadeout.  Default value is 3 seconds.
.TP
\fI\-g subsong\-gap\fR
Set subsong gap to \fIsubsong\-gap\fR seconds.  Before playing the next subsong after the subsong timeout, play \fIsubsong\-gap\fR seconds of silence.  Default value is 2 seconds.
.TP
\fI\-h\fR
Display short help and exit.
.TP
\fI\-l\fR
Enable loop mode.  When the last subsong is played, playback starts again with the first subsong.  Default is no loop.
.TP
\fI\-o plugin\fR
Select sound output plugin \fIplugin\fR.  Default depends on compilation options.  Select \fIlist\fR to view a list of all available output plugins.
.TP
\fI\-q\fR
Be quiet, show only error messages.
.TP
\fI\-r samplerate\fR
Set the samplerate to \fIsamplerate\fR Hz.  Default value is 44100Hz.
.TP
\fI\-R refresh\-delay\fR
Set the refresh delay to \fIrefresh\-delay\fR milliseconds.  Default value is 33 milliseconds.  Larger values will lower CPU usage, but things as subsong changes, fadeouts, reactions to keypresses and the on\-screen display will be delayed.
.TP
\fI\-t subsong\-timeout\fR
Set subsong timeout to \fIsubsong\-timeout\fR seconds.  When a subsong has been played for the given time, the player will skip to the next subsong.  Default value is 120 seconds.
.TP
\fI\-T silence\-timeout\fR
Set silence timeout to \fIsilence\-timeout\fR seconds.  When a subsong contains silence for the given time, the player will skip to the next subsong.  Default value is 2 seconds.
.TP
\fI\-V\fR
Display version number and exit.
.TP
\fI\-z\fR
Play subsongs in shuffle mode.  Every subsong will be played once in random order.
.TP
\fI\-Z\fR
Play subsongs in random mode.  Like shuffle mode, but a subsong can be played multiple times.
.SH "PARAMETERS"
.TP
\fIgbs\-file\fR
The sound file to play.  Must be in uncompressed .GBS format.
.TP
\fIstart\-subsong\fR
The subsong from the sound file to play.  If not specified, the default song will be played (unless in shuffle or random mode).  An out\-of\-bounds number will be clipped to the possible range of subsongs.
.TP
\fIstop\-subsong\fR
gbsplay stops when this subsong has been played.  If not specified or out-of-bound, gbsplay will stop after playing the last subsong.
.SH "KEYBOARD CONTROL"
\fBgbsplay\fR supports basic keyboard control.  The following commands are recognized:
.TP
\fIp\fR
Skip to the previous subsong.
.TP
\fIn\fR
Skip to the next subsong.
.TP
\fIq\fR or \fIEsc\fR
Quit gbsplay.
.TP
\fISpace\fR
Toggle play/pause.
.TP
\fI1\fR
Mute/unmute channel 1.
.TP
\fI2\fR
Mute/unmute channel 2.
.TP
\fI3\fR
Mute/unmute channel 3.
.TP
\fI4\fR
Mute/unmute channel 4.
.SH "FILES"
.TP
\fI/etc/gbsplayrc\fR
Default location of the global configuration file.
.TP
\fI~/\.gbsplayrc\fR
User configuration file.
.SH "SEE ALSO"
\fIgbsinfo\fR(1)
\fIgbsplayrc\fR(5)
.SH "BUG REPORTS"
If you encounter bugs, please report them via \fIhttp://gbsplay.berlios.de/\fR or write to <\fIgbsplay-dev@lists.berlios.de\fR>.
.SH "AUTHOR"
gbsplay was written by Tobias Diedrich <\fIranma@gmx.at\fR> (with contributions from others, see README).
.SH "COPYRIGHT"
gbsplay is licensed under GNU GPL.
