.\" This manpage 2003 (C) by Christian Garbs <mitch@cgarbs.de>
.\" Licensed under GNU GPL.
.TH "gbsplay" "1" "0.0.0" "Tobias Diedrich" "Gameboy sound player"
.SH "NAME"
.LP
\fBgbsplay\fR \- Gameboy sound player
.SH "SYNOPSIS"
\&\fBgbsplay\fR \fIgbs\-file\fR [\fIsubsong\fR]
.SH "DESCRIPTION"
gbsplay emulates the sound hardware of the Nintendo Gameboy.  It
is able to play the sounds from a Gameboy module dump (.GBS format)
over /dev/dsp.
.SH "PARAMETERS"
.TP
\fIgbs\-file\fR
The sound file to play.  Must be in uncompressed .GBS format.
.TP
\fIsubsong\fR
The subsong from the sound file to play.  If nothing is specified, the default song will be played.  An out\-of\-bounds number will result in an error.
.SH "SEE ALSO"
\fIgbsinfo\fR(1)
.SH "BUG REPORS"
If you encounter bugs, please report them to <\fIranma@gmx.at\fR>.
.SH "AUTHOR"
gbsplay was written by Tobias Diedrich <\fIranma@gmx.at\fR> (with contributions from others, see README).
.SH "COPYRIGHT"
gbsplay is licensed under GNU GPL.
