.\" $Id: gbsplay.in.1,v 1.2 2003/10/11 17:45:55 mitch Exp $
.\" This manpage 2003 (C) by Christian Garbs <mitch@cgarbs.de>
.\" Licensed under GNU GPL.
.TH "gbsplay" "1" "%%%VERSION%%%" "Tobias Diedrich" "Gameboy sound player"
.SH "NAME"
.LP
\fBgbsplay\fR \- Gameboy sound player
.SH "SYNOPSIS"
\fBgbsplay\fR [\fI\-h\fR] [\fI\-r samplerate\fR] [\fI\-s\fR] [\fI\-t subsong\-timeout\fR] [\fI\-T silence\-timeout\fR] [\fI\-V\fR] \fIgbs\-file\fR [\fIstart\-subsong\fR [\fIstop\-subsong\fR] ]
.SH "DESCRIPTION"
gbsplay emulates the sound hardware of the Nintendo Gameboy.  It
is able to play the sounds from a Gameboy module dump (.GBS format)
over /dev/dsp.
.SH "OPTIONS"
.TP
\fI\-h\fR
Display short help and exit.
.TP
\fI\-q\fR
Be quiet, show only error messages.
.TP
\fI\-r samplerate\fR
Set the samplerate to \fIsamplerate\fR Hz.  Default value is 44100Hz.
.TP
\fI\-s\fR
Write to stdout instead of /dev/dsp.
.TP
\fI\-t subsong\-timeout\fR
Set subsong timeout to \fIsubsong\-timeout\fR seconds.  When a subsong has been played for the given time, the player will skip to the next subsong.  Default value is 120 seconds.
.TP
\fI\-T silence\-timeout\fR
Set silence timeout to \fIsilence\-timeout\fR seconds.  When a subsong contains silence for the given time, the player will skip to the next subsong.  Default value is 2 seconds.
.TP
\fI\-V\fR
Display version number and exit.
.TP
\fI\-z\fR
Play subsongs in random mode.  Every subsong will be played once in random order.
.TP
\fI\-Z\fR
Play subsongs in shuffle mode.  Like random mode, but a subsong can be played multiple times.
.SH "PARAMETERS"
.TP
\fIgbs\-file\fR
The sound file to play.  Must be in uncompressed .GBS format.
.TP
\fIstart\-subsong\fR
The subsong from the sound file to play.  If not specified, the default song will be played (unless in shuffle or random mode).  An out\-of\-bounds number will be clipped to the possible range of subsongs.
.TP
\fIstop\-subsong\fR
gbsplay stops when this subsong has been played.  If not specified or out-of-bound, gbsplay will stop after playing the last subsong.
.SH "KEYBOARD CONTROL"
\fBgbsplay\fR supports basic keyboard control.  The following commands are recognized:
.TP
\fIp\fR
Skip to the previous subsong.
.TP
\fIn\fR
Skip to the next subsong.
.TP
\fIq\fR or \fIEsc\fR
Quit gbsplay.
.SH "FILES"
.TP
\fI/etc/gbsplayrc\fR
Default location of the global configuration file.
.TP
\fI~/\.gbsplayrc\fR
User configuration file.
.SH "SEE ALSO"
\fIgbsinfo\fR(1)
\fIgbsplayrc\fR(5)
.SH "BUG REPORTS"
If you encounter bugs, please report them to <\fIranma@gmx.at\fR>.
.SH "AUTHOR"
gbsplay was written by Tobias Diedrich <\fIranma@gmx.at\fR> (with contributions from others, see README).
.SH "COPYRIGHT"
gbsplay is licensed under GNU GPL.
