.\" $Id: gbsplayrc.in.5,v 1.12 2004/06/27 14:47:53 mitch Exp $
.\" This manpage 2003-2004 (C) by Christian Garbs <mitch@cgarbs.de>
.\" Licensed under GNU GPL.
.TH "gbsplayrc" "5" "%%%VERSION%%%" "Tobias Diedrich" "Gameboy sound player"
.SH "NAME"
.LP
\fBgbsplayrc\fR \- Gameboy sound player configuration file
.SH "DESCRIPTION"
\fI/etc/gbsplayrc\fR and \fI~/\.gbsplayrc\fR are used by gbsplay(1).
.SH "SYNTAX"
Comments are introduced by hash marks.  A comment continues to the end of the line.  Whitespace, including empty lines, is ignored.  Option values follow the option name and an equal sign.  Valid option value types are:
.IP Boolean
An integer number in decimal. 0 is considered \fIfalse\fR, everything else is \fItrue\fR.
.IP Endian
A single character denoting the endianness. n == native endian, l == little endian and b == big endian.
.IP Integer
An integer number in decimal.
.IP Plugin
The name of an output plugin.  Run \fIgbsplay -o list\fR to get a list of all available output plugins.
.SH "OPTIONS"
.IP "endian = \fIEndian\fR"
The output endianness.
.IP "fadeout = \fIInteger\fR"
The fadeout time in seconds.  Instead of cutting of the subsong hard, do a soft fadeout.
.IP "loop = \fIBoolean\fR"
In loop mode the playback will restart from the beginning after the last subsong.
.IP "output_plugin = \fIPlugin\fR"
The sound output plugin to be used.
.IP "rate = \fIInteger\fR"
The samplerate to be used.
.IP "refresh_delay = \fIInteger\fR"
Set the refresh delay in milliseconds.  Larger values will lower CPU usage, but things as subsong changes, fadeouts, reactions to keypresses and the on\-screen display will be delayed.
.IP "silence_timeout = \fIInteger\fR"
The silence timeout in seconds.  When a subsong contains silence for the given
time, the player will skip to the next subsong.
.IP "subsong_gap = \fIInteger\fR"
The subsong gap in seconds.  Before playing the next subsong after the subsong timeout, play \fIsubsong_gap\fR seconds of silence.
.IP "subsong_timeout = \fIInteger\fR"
The subsong timeout in seconds.  When a subsong has been played for the given
time, the player will skip to the next subsong.  A timeout of 0 seconds disables automatic subsong changes.
.IP "verbosity = \fIInteger\fR"
Sets the verbosity level (default: 3). A value of 0 means no messages on stdout.
.SH "FILES"
.TP
\fI/etc/gbsplayrc\fR
Default location of the global configuration file.
.TP
\fI~/\.gbsplayrc\fR
User configuration file.
.SH "SEE ALSO"
\fIgbsplay\fR(1),
\fIgbsinfo\fR(1)
.SH "BUG REPORTS"
If you encounter bugs, please report them via \fIhttp://gbsplay.berlios.de/\fR or write to <\fIgbsplay-dev@lists.berlios.de\fR>.
.SH "AUTHOR"
gbsplay was written by Tobias Diedrich <\fIranma@gmx.at\fR> (with contributions from others, see README).
.SH "COPYRIGHT"
gbsplay is licensed under GNU GPL.
