# This workflow will build and test gbsplay in various configurations on macOS.

name: macOS Build

on:
  push:
  pull_request:
    types: [opened]
  schedule:
    - cron: '23 4 5 * *'

jobs:
  build-macos:
    name: Build and test on macOS

    runs-on: macos-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        flags: [--enable-verbosebuild]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install sdl2
    - name: Build and test
      env:
        CC: ${{ matrix.compiler }}
        CONFIGURE_FLAGS: ${{ matrix.flags }}
      run: |
        make
    - name: Check activated plugouts
      run: |
        ./check_plugouts.sh sdl
    - name: Check build flags
      run: |
        ./check_buildflags.sh ${{ matrix.flags }}
    - name: Dump configure on error
      if: ${{ failure() }}
      run: |
        bash -x -v configure && cat config.err
