# This workflow will build and test gbsplay in various configurations on Windows.

name: Windows Build

on:
  push:
  pull_request:
    types: [opened]
  schedule:
    - cron: '23 4 5 * *'

jobs:
  build-windows:
    name: Build and test on Windows

    runs-on: windows-latest

    strategy:
      matrix:
        type: [MINGW64]
        flags: ['LDFLAGS=-static']
        include:
          - type: MINGW64
            msystem: true
            packages: mingw-w64-x86_64-toolchain groff
            plugouts: dsound
            shell: msys2 {0}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - uses: actions/checkout@v4
    - if: ${{ matrix.msystem }}
      name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.type }}
        install: git base-devel ${{ matrix.packages }} zlib-devel dos2unix
        release: false
        update: false
    - name: Build and test
      env:
        CONFIGURE_FLAGS: ${{ matrix.flags }} --enable-verbosebuild --build=x86_64-w64-mingw32
      run: |
        make
    - name: prepare artifacts
      run: |
        version=$(sed -n "/^VERSION/s/.* //p" config.mk)
        output_dir=gbsplay-${version}

        echo create artifact directory ${output_dir}/"
        mkdir -p artifacts/${output_dir}/

        echo "copy binaries"
        cp -v gbsplay.exe gbsinfo.exe ${output_dir}/
        
        for manpage in gbsinfo gbsplay gbsplayrc; do
            echo format manpage ${manpage}"
            groff -Tascii -P-c -P-b -P-u -man man/${manpage}.? > ${output_dir}/${manpage}.txt
        done

        echo "copy README"
        grep -v '^\[!\[' README.md > ${output_dir}/README.txt

        echo "copy HISTORY"
        cat HISTORY > ${output_dir}/HISTORY.txt
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gbsplay windows
        path: artifacts/
        if-no-files-found: error
        retention-days: 7 # don't hog resources, real builds are attached to the release anyway
        compression-level: 9 # we seldom release, so try as hard as we can
